### ISSUE TITLE
VCamera Groups

### ISSUE THREAD

**Issue by aXu-AP** [BtheDestroyer/GodotVCamera#16]
**Is your feature request related to a problem? Please describe.**
Currently the system cannot be used for splitscreen multiplayer or other scenarios which ask for multiple cameras.

**Describe the solution you'd like**
Add groups/layers option to VCamera and VCameraBrain. VCameraBrain will take into account only VCameras which have corresponding group. The question is, which type is this group.
 - It could be integer value (group 1, 2, 3...), which is easy to set and lends itself naturally to multiplayer scenario.
 - String groups are another choice. 
 - Third option is to use bitwise flags like collision masks.
 - Fourth, more unobtrusive way is to let user define add VCameras to groups of their choise via Godot's built-in groups. This is good, since the system already uses groups to find virtual cameras and it won't overwhelm new users with multitude of options. Thus no change to VCamera is needed, only to VCameraBrain.
VCamera should be possible to add into multiple groups, as certain viewpoints can be shared between players. Third and fourth options give this function for free.

**Comment by aXu-AP** [comment]
After trying it in practice (see #17), I liked the fourth option to be easy to use and flexible.

**Comment by Bryce-Dixon** [comment]
Merged #17

**Comment by Bryce-Dixon** [comment]
I'd also like to at some point add dynamic splitscreen as described by Squirrel Eiserloh in this GDC talk (25:30): https://www.youtube.com/watch?v=tu-Qe66AvtY

**Comment by aXu-AP** [comment]
That's a great talk! I have a feeling that's going to be a tough one to solve in 3D...
