### ISSUE TITLE
Two space indentation

### ISSUE THREAD

**Issue by aXu-AP** [BtheDestroyer/GodotVCamera#7]
**Describe the bug**
This is more of a problem within Godot itself, but as default settings for indentation in Godot are tabs, size 4, _convert indent on save_, opening a script and then saving/running a scene causes opened scripts to be corrupted. Some indentations get converted to tabs, some don't (4 spaces get converted, 2 don't). As a result, script will contain mixed indentation of tabs and spaces and that's not allowed in gdscript.

**To Reproduce**
Open project in Godot with default settings. Open any script from the project, then run.  Godot can't run the project.

**Additional context**
See [Godot issue](https://github.com/godotengine/godot/issues/35007) for more thorough explanation regarding this bug. The issue doesn't seem to be high on priority, since the issue has been open for more than 2 years and has very little activity (I guess most use default settings or 4 spaces, so it doesn't come up often)...
Until it gets fixed I'd recommend using tabs for indentation for addon development or disclaimer about the problem in readme.

On a side note, cool addon! I have thought about making something like this for a while, so I'll look forward using this :)

**Comment by Bryce-Dixon** [comment]
I ran into this issue when helping a friend get setup with another addon of mine.
It's definitely a little painful for me that this is the case, but it is what it is: plugins should stick to the default setting of single tabs instead of 2 spaces.

**Comment by Bryce-Dixon** [comment]
I merged your PR which should solve this issue. Thanks for the contribution!

**Comment by aXu-AP** [comment]
Thanks for understanding, I know each of us would like to stick with their preferences :)
Godot would benefit from per-project setting for this...
