### ISSUE TITLE
Renaming Effect

### ISSUE THREAD

**Issue by aXu-AP** [BtheDestroyer/GodotVCamera#9]
**Is your feature request related to a problem? Please describe.**
Effect is quite generic name and likely to conflict with user's own classes. Also it could refer to post-processing effects, particle effects, potion effects etc.

**Describe the solution you'd like**
Rename `Effect` class to something that better represents its function. Best I could come up with is `CameraModifier`. Modifier sounds like something you can stack (at least to anybody familiar with Blender), conveying this side of these nodes well.

**Describe alternatives you've considered**
`TransformModifier` and `CameraEffect` could be valid too. I prefer to have camera in the name in case there will be some camera specific functionality, like zooming.

**Comment by Bryce-Dixon** [comment]
I agree that `TransformModifier` would be a much better name. I originally went with `Effect` because `CameraModifier` seemed too restrictive (eg: it sounds like it only works for cameras)

**Comment by Bryce-Dixon** [comment]
Fixed as of commit 4fe39c3e3516fd880052094ad35805afd2d9dd04
